apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe 
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  policies:
  - name: cafe-policy
  upstreams:
  - name: coffee 
    service: coffee-svc
    port: 80
  routes:
  - path: /
    action:
      pass: coffee
