---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings-nap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-nap
  labels:
    app: ratings-nap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-nap
  template:
    metadata:
      labels:
        app: ratings-nap
    spec:
      serviceAccountName: bookinfo-ratings-nap
      containers:
      - name: ratings-nap
        image: app-protect:216
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 9080
      volumes:
      - name: config-volume
        configMap:
          name: bookinfo-default-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookinfo-default-conf
data:
  nginx.conf: |-

    user nginx;
    
    worker_processes 1;
    load_module modules/ngx_http_app_protect_module.so;
    
    error_log /var/log/nginx/error.log debug;
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        proxy_http_version 1.1;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent"';
    
        upstream internalApp {
           server ratings-hidden:9080;
        }
    
        server {
            listen       9080;
            app_protect_enable on;
            app_protect_security_log_enable on;
            app_protect_security_log "/etc/nginx/log-default.json" syslog:server=10.1.1.5:5144;
            app_protect_policy_file "/etc/nginx/NginxDefaultPolicy.json";
    
            location / {
                proxy_pass http://internalApp;
            }
        }
    }

---
